spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes[0]:
          id: bff-service
          uri: http://bff-service:8084
          predicates:
            - Path=/api/bff/**

server:
  port: 8080
