spring:
  application:
    name: bff-service

server:
  port: 8084

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      inventoryService:
        baseConfig: default
      orderService:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
    instances:
      inventoryService:
        baseConfig: default
      orderService:
        baseConfig: default

INVENTORY_SERVICE_URL: http://inventory-service:8081
ORDER_SERVICE_URL: http://order-service:8082
