spring:
  application:
    name: order-service
  datasource:
    url: ${DB_ORDERS_URL:jdbc:postgresql://localhost:5433/order_db}
    username: ${DB_ORDERS_USER:postgres}
    password: ${DB_ORDERS_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${ORDER_PORT:8082}

INVENTORY_SERVICE_URL: ${INVENTORY_URL:http://localhost:8081}
