spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://inventory-db:5432/inventory
    username: inventory_user
    password: inventory_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
